name:"Story for Project my-app"
description: "Use this template to create new story with some Tasks"
title: "[User Story]: "
labels: ["Story"]
assignees:
  - "{{ elnsor }}"  
projects: ["my-app"]
body:
    - type: input
      id: main_issue_title
      attributes:
        label: "Name of this Story"
        description: "Nice Clear Titel"
        placeholder: "Name of Story"

  - type: textarea
    id: main_issue_description
    attributes:
      label: "Describe"
      description: "add imformative description"
      placeholder: "add some description"

  - type: markdown
    attributes:
      value: "### 🧩 Tasks"

  - type: textarea
    id: subissues
    attributes:
      label: "Tasks List"
      description: "Add each task in new line"
      placeholder: |
        Task 1
        Task 2
        Task 3
  
