name:  "user Story Template"
description: "For create user Story" 
title: "User Story"
labels: ["Story"]
assignees: ["elnsor"]
projects: ["may-app"] 
body:
  - type: markdown 
    attributes:
      value: "ℹ️ Story information"
  - type: input 
    id: id_mdetail 
    attributes:
      label: "detail"
      description: "enter breif details "
      placeholder: "come place holder in input"
  - type: textarea
    id: text_id 
    label: "Descriptions"
    description: "step for creation this story" 
    placeholder: "Mor details"
  - type: markdown
    attributes:
      value: "___" 
  - type: markdown
    attributes:
      value: "## Add SubTask"
  - type: textarea
    id: text_subtask 
    label: "SubTasks"
    description: "add check list for subissues"
    value: |
            add tasks 
            - [] Task1
            - [] Task2 
            - [] Task3 
            - [] ... 
